basePath: /
definitions:
  advertapi.AdvertRequest:
    properties:
      href:
        description: 跳转链接
        type: string
      images:
        description: 图片
        type: string
      is_show:
        description: 是否展示
        type: boolean
      title:
        description: 显示的标题
        type: string
    required:
    - href
    - images
    - title
    type: object
  ctype.ImageType:
    enum:
    - 1
    - 2
    type: integer
    x-enum-comments:
      Local: ImageType
      QiNiu: ImageType
    x-enum-varnames:
    - Local
    - QiNiu
  imagesapi.ImageUpdateRequest:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - id
    - name
    type: object
  imagesapi.ImagesResponse:
    properties:
      id:
        type: integer
      name:
        description: 图片名称
        type: string
      path:
        description: 图片路径
        type: string
    type: object
  imageser.FileUploadResponse:
    properties:
      file_name:
        description: 文件名
        type: string
      is_success:
        description: 是否上传成功
        type: boolean
      msg:
        description: 消息
        type: string
    type: object
  menuapi.Banner:
    properties:
      id:
        type: integer
      path:
        type: string
    type: object
  menuapi.ImageSort:
    properties:
      image_id:
        type: integer
      sort:
        type: integer
    type: object
  menuapi.MenuNameResponse:
    properties:
      id:
        type: integer
      path:
        type: string
      title:
        type: string
    type: object
  menuapi.MenuRequest:
    properties:
      abstract:
        items:
          type: string
        type: array
      abstract_time:
        description: 切换的时间，单位秒
        type: integer
      banner_time:
        description: 切换的时间，单位秒
        type: integer
      image_sort_list:
        description: 具体图片的顺序
        items:
          $ref: '#/definitions/menuapi.ImageSort'
        type: array
      path:
        type: string
      slogan:
        type: string
      sort:
        description: 菜单的序号
        type: integer
      title:
        type: string
    required:
    - path
    - sort
    - title
    type: object
  menuapi.MenuResponse:
    properties:
      abstract:
        description: 简介
        items:
          type: string
        type: array
      abstract_time:
        description: 简介的切换时间
        type: integer
      banner_time:
        description: 菜单图片的切换时间 为 0 表示不切换
        type: integer
      banners:
        items:
          $ref: '#/definitions/menuapi.Banner'
        type: array
      created_at:
        description: 创建时间
        type: string
      id:
        description: 主键ID
        type: integer
      path:
        type: string
      slogan:
        description: slogan
        type: string
      sort:
        description: 菜单的顺序
        type: integer
      title:
        type: string
      updated_at:
        description: 更新时间
        type: string
    type: object
  models.AdvertModel:
    properties:
      created_at:
        description: 创建时间
        type: string
      href:
        description: 跳转链接
        type: string
      id:
        description: 主键ID
        type: integer
      images:
        description: 图片
        type: string
      is_show:
        description: 是否展示
        type: boolean
      title:
        description: 显示的标题
        type: string
      updated_at:
        description: 更新时间
        type: string
    type: object
  models.BannerModel:
    properties:
      created_at:
        description: 创建时间
        type: string
      hash:
        description: 图片的hash值，用于判断重复图片
        type: string
      id:
        description: 主键ID
        type: integer
      image_type:
        allOf:
        - $ref: '#/definitions/ctype.ImageType'
        description: 图片的类型， 本地还是七牛
      name:
        description: 图片名称
        type: string
      path:
        description: 图片路径
        type: string
      updated_at:
        description: 更新时间
        type: string
    type: object
  models.RemoveRequest:
    properties:
      id_list:
        description: 要删除的记录id
        items:
          type: integer
        type: array
    type: object
  res.ListResponse-models_AdvertModel:
    properties:
      count:
        type: integer
      list:
        $ref: '#/definitions/models.AdvertModel'
    type: object
  res.ListResponse-models_BannerModel:
    properties:
      count:
        type: integer
      list:
        $ref: '#/definitions/models.BannerModel'
    type: object
  res.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
host: 10.0.0.3:8080
info:
  contact: {}
  description: API文档
  title: gvb-blog文档
  version: "1.0"
paths:
  /api/adverts:
    delete:
      description: 批量删除广告
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 广告id列表
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.RemoveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 批量删除广告
      tags:
      - 广告管理
    get:
      description: 广告列表
      parameters:
      - description: 模糊查询使用的关键字
        in: query
        name: key
        type: string
      - description: 一页限制多少记录
        in: query
        name: limit
        type: integer
      - description: 从第几页开始，后续会生成offset
        in: query
        name: page
        type: integer
      - description: 排序字段
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  $ref: '#/definitions/res.ListResponse-models_AdvertModel'
              type: object
      summary: 广告列表
      tags:
      - 广告管理
    post:
      description: 创建广告
      parameters:
      - description: 表示多个参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/advertapi.AdvertRequest'
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 创建广告
      tags:
      - 广告管理
  /api/adverts/{id}:
    put:
      description: 更新广告
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 广告的一些参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/advertapi.AdvertRequest'
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 更新广告
      tags:
      - 广告管理
  /api/images:
    delete:
      description: 删除图片
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 图片id列表
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.RemoveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 删除图片
      tags:
      - 图片管理
    get:
      description: 图片列表
      parameters:
      - description: 模糊查询使用的关键字
        in: query
        name: key
        type: string
      - description: 一页限制多少记录
        in: query
        name: limit
        type: integer
      - description: 从第几页开始，后续会生成offset
        in: query
        name: page
        type: integer
      - description: 排序字段
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  $ref: '#/definitions/res.ListResponse-models_BannerModel'
              type: object
      summary: 图片列表
      tags:
      - 图片管理
    post:
      description: 上传图片
      parameters:
      - description: 上传的图片文件
        in: formData
        name: data
        required: true
        type: file
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  $ref: '#/definitions/imageser.FileUploadResponse'
              type: object
      summary: 上传图片
      tags:
      - 图片管理
    put:
      description: 更新图片
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 图片的一些参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/imagesapi.ImageUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 更新图片
      tags:
      - 图片管理
  /api/images_names:
    get:
      description: 图片名称列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  $ref: '#/definitions/imagesapi.ImagesResponse'
              type: object
      summary: 图片名称列表
      tags:
      - 图片管理
  /api/menus:
    delete:
      description: 删除菜单
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 图片id列表
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.RemoveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 删除菜单
      tags:
      - 菜单管理
    get:
      description: 菜单列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  $ref: '#/definitions/menuapi.MenuResponse'
              type: object
      summary: 菜单列表
      tags:
      - 菜单管理
    post:
      description: 添加菜单
      parameters:
      - description: 表示多个参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/menuapi.MenuRequest'
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 添加菜单
      tags:
      - 菜单管理
    put:
      description: 更新菜单
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 图片的一些参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/menuapi.MenuRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 更新菜单
      tags:
      - 菜单管理
  /api/menus/{id}:
    get:
      description: 菜单细节
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  $ref: '#/definitions/menuapi.MenuResponse'
              type: object
      summary: 菜单细节
      tags:
      - 菜单管理
  /api/menus_names:
    get:
      description: 菜单名称列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  $ref: '#/definitions/menuapi.MenuNameResponse'
              type: object
      summary: 菜单名称列表
      tags:
      - 菜单管理
swagger: "2.0"
